"""Declarative base and shared ORM conventions."""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Explicit naming convention so autogenerated Alembic migrations produce
# stable, predictable constraint/index names across environments.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Server-generated/`onupdate` column values (created_at, updated_at)
    # are fetched back via RETURNING as part of the same INSERT/UPDATE,
    # instead of being marked expired-pending-refresh. Without this, an
    # attribute access on such a column after a flush — e.g. serializing
    # to a Pydantic schema right after a service-layer create-then-update
    # in one request — raises `MissingGreenlet`: AsyncSession only allows
    # DB IO from an awaited call, and a later plain attribute access
    # isn't one.
    __mapper_args__ = {"eager_defaults": True}


# Import domain models here (or in their own modules re-exported through
# `app.models`) so Alembic's `--autogenerate` can discover them via
# `Base.metadata`.
