"""add scan job outbox table

Revision ID: a1fb5cd36013
Revises: b3214246fc2f
Create Date: 2026-07-25 14:18:14.422598
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1fb5cd36013"
down_revision: str | None = "b3214246fc2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_job_outbox",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("scan_attempt", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("countdown_seconds", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_scan_job_outbox_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "countdown_seconds >= 0",
            name=op.f("ck_scan_job_outbox_countdown_seconds_non_negative"),
        ),
        sa.CheckConstraint(
            "payload IS NULL OR pg_column_size(payload) <= 4096",
            name=op.f("ck_scan_job_outbox_payload_size_limit"),
        ),
        sa.CheckConstraint(
            "scan_attempt >= 0", name=op.f("ck_scan_job_outbox_scan_attempt_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "scan_id"],
            ["scans.tenant_id", "scans.id"],
            name="fk_scan_job_outbox_tenant_id_scan_id_scans",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_scan_job_outbox_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_job_outbox")),
        sa.UniqueConstraint(
            "tenant_id",
            "scan_id",
            "scan_attempt",
            name="uq_scan_job_outbox_tenant_scan_attempt",
        ),
    )
    op.create_index(
        "ix_scan_job_outbox_pending",
        "scan_job_outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_scan_job_outbox_pending",
        table_name="scan_job_outbox",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("scan_job_outbox")
    # ### end Alembic commands ###
