"""add scan orchestration fields and scan_events table

Revision ID: b3214246fc2f
Revises: af3a58d67429
Create Date: 2026-07-25 09:57:10.692922
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3214246fc2f"
down_revision: str | None = "af3a58d67429"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=True),
        sa.Column("worker_id", sa.String(length=200), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("message", sa.String(length=2000), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            # clock_timestamp(), not now(): see app/models/scan_event.py —
            # one scan's whole run shares a single transaction, so now()
            # would give every ScanEvent it creates the same timestamp.
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "metadata IS NULL OR pg_column_size(metadata) <= 8192",
            name=op.f("ck_scan_events_metadata_size_limit"),
        ),
        sa.CheckConstraint(
            "progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)",
            name=op.f("ck_scan_events_progress_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "scan_id"],
            ["scans.tenant_id", "scans.id"],
            name="fk_scan_events_tenant_id_scan_id_scans",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_scan_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_events")),
    )
    op.add_column("scans", sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("scans", sa.Column("timed_out_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("scans", sa.Column("attempt", sa.Integer(), server_default="0", nullable=False))
    op.add_column(
        "scans", sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False)
    )
    op.add_column("scans", sa.Column("worker_id", sa.String(length=200), nullable=True))
    op.add_column("scans", sa.Column("job_id", sa.String(length=200), nullable=True))
    op.add_column(
        "scans", sa.Column("timeout_seconds", sa.Integer(), server_default="1800", nullable=False)
    )
    op.add_column("scans", sa.Column("retry_of_scan_id", sa.UUID(), nullable=True))
    op.add_column(
        "scans", sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("scans", sa.Column("correlation_id", sa.String(length=100), nullable=True))
    op.create_foreign_key(
        "fk_scans_tenant_id_retry_of_scan_id_scans",
        "scans",
        "scans",
        ["tenant_id", "retry_of_scan_id"],
        ["tenant_id", "id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # --- Hand-written: autogenerate does not reliably diff CHECK
    # constraints (see CLAUDE.md's standing migration-review rule). The
    # native_enum=False/create_constraint=True enum pattern means adding
    # PREPARING/COLLECTING/PROCESSING/TIMED_OUT to ScanStatus is a
    # DROP/CREATE CONSTRAINT here, not an ALTER TYPE. The old
    # completed/failed-only mutual-exclusion check is generalized to all
    # four terminal timestamps (see app/models/scan.py). ---
    op.drop_constraint(op.f("ck_scans_scan_status"), "scans", type_="check")
    op.create_check_constraint(
        op.f("ck_scans_scan_status"),
        "scans",
        "status IN ('PENDING', 'QUEUED', 'PREPARING', 'RUNNING', 'COLLECTING', "
        "'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT')",
    )

    op.drop_constraint(op.f("ck_scans_completed_failed_mutually_exclusive"), "scans", type_="check")
    op.create_check_constraint(
        op.f("ck_scans_terminal_timestamps_mutually_exclusive"),
        "scans",
        "(CASE WHEN completed_at IS NOT NULL THEN 1 ELSE 0 END"
        " + CASE WHEN failed_at IS NOT NULL THEN 1 ELSE 0 END"
        " + CASE WHEN cancelled_at IS NOT NULL THEN 1 ELSE 0 END"
        " + CASE WHEN timed_out_at IS NOT NULL THEN 1 ELSE 0 END) <= 1",
    )

    op.create_check_constraint(
        op.f("ck_scans_timed_out_after_started"),
        "scans",
        "timed_out_at IS NULL OR started_at IS NULL OR timed_out_at >= started_at",
    )
    op.create_check_constraint(op.f("ck_scans_attempt_non_negative"), "scans", "attempt >= 0")
    op.create_check_constraint(op.f("ck_scans_max_attempts_positive"), "scans", "max_attempts >= 1")
    op.create_check_constraint(
        op.f("ck_scans_timeout_seconds_positive"), "scans", "timeout_seconds > 0"
    )
    op.create_check_constraint(
        op.f("ck_scans_config_size_limit"),
        "scans",
        "config IS NULL OR pg_column_size(config) <= 16384",
    )


def downgrade() -> None:
    # --- Hand-written: reverse of the hand-written CHECK-constraint
    # changes above, before the autogenerated column drops. ---
    op.drop_constraint(op.f("ck_scans_config_size_limit"), "scans", type_="check")
    op.drop_constraint(op.f("ck_scans_timeout_seconds_positive"), "scans", type_="check")
    op.drop_constraint(op.f("ck_scans_max_attempts_positive"), "scans", type_="check")
    op.drop_constraint(op.f("ck_scans_attempt_non_negative"), "scans", type_="check")
    op.drop_constraint(op.f("ck_scans_timed_out_after_started"), "scans", type_="check")

    op.drop_constraint(
        op.f("ck_scans_terminal_timestamps_mutually_exclusive"), "scans", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_scans_completed_failed_mutually_exclusive"),
        "scans",
        "completed_at IS NULL OR failed_at IS NULL",
    )

    op.drop_constraint(op.f("ck_scans_scan_status"), "scans", type_="check")
    op.create_check_constraint(
        op.f("ck_scans_scan_status"),
        "scans",
        "status IN ('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_scans_tenant_id_retry_of_scan_id_scans", "scans", type_="foreignkey")
    op.drop_column("scans", "correlation_id")
    op.drop_column("scans", "config")
    op.drop_column("scans", "retry_of_scan_id")
    op.drop_column("scans", "timeout_seconds")
    op.drop_column("scans", "job_id")
    op.drop_column("scans", "worker_id")
    op.drop_column("scans", "max_attempts")
    op.drop_column("scans", "attempt")
    op.drop_column("scans", "timed_out_at")
    op.drop_column("scans", "cancelled_at")
    op.drop_table("scan_events")
    # ### end Alembic commands ###
