apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinelx-production
nameSuffix: -production

resources:
  - ../../base

configMapGenerator:
  - name: sentinelx-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_FORMAT=json
      - NEXT_PUBLIC_API_BASE_URL=https://api.sentinelx.io/api/v1
      - NEXT_PUBLIC_APP_ENV=production

images:
  - name: ghcr.io/sentinelx/backend
    newTag: latest
  - name: ghcr.io/sentinelx/frontend
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: "^(backend|frontend)$"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: "^worker$"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: Deployment
      name: "^backend$"
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
